// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqqrejogbkbkecsrdatq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxcXJlam9nYmtia2Vjc3JkYXRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NTgxOTAsImV4cCI6MjA2MTMzNDE5MH0.moBRJ4fMLHqdlMC_BktZlQnRz0kEnALE7QrWmxEfzJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);